# Generated by Django 3.2.8 on 2025-11-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
    ]
