# Generated by Django 3.2.8 on 2025-11-19 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20251119_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='users',
            field=models.ManyToManyField(related_name='films', through='films.UserFilms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='users',
            field=models.ManyToManyField(related_name='films', through='films.UserFilms', to=settings.AUTH_USER_MODEL),
        ),
    ]
