# Generated by Django 3.2.8 on 2025-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='film_photos/'),
        ),
    ]
